name: fangorn
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  benchmark_harness: ^2.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.16.7
